name: NodeJS with Gulp

on:
  push:
    branches: [ "codespace-emanisay27-verbose-disco-x6gg655ggvr3vj4g" ]
  pull_request:
    branches: [ "codespace-emanisay27-verbose-disco-x6gg655ggvr3vj4g" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        gulp
